spring:
  application:
    name: user-center-backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: 'your username of database'
    password: 'your password of database'
    url: 'your database url in production environment'
  # session timeout
  session:
    timeout: 86400